### PR TITLE
Add support section to README

### PR DESCRIPTION
**Pull request by jeremygoldsmith**
## Description of the change
Adding a support section with our support@stackhawk.com email address.

> Description here

everyone needs support

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> [ISSUE-ID](https://<ORG>.atlassian.net/browse/ISSUE-ID)

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by zconger — APPROVED** [review]
LGTM!

See the `.github/CONTRIBUTING.md` guide for getting this version-revved and published up to the Github Actions marketplace. Or let me know and I can give you a guided tour, or handle it.

**Comment by jeremygoldsmith** [comment]
@zconger do I need to bump the version number if all I'm doing is just updating the README?

**Comment by zconger** [comment]
> @zconger do I need to bump the version number if all I'm doing is just updating the README?

Yes, if you want it published to the GitHub marketplace. Publishing the README to the marketplace requires a version bump.

**Review by zconger — APPROVED** [review]
`maxkaakaww`

**Pull request merged**
